name: V2Ray Auto Post
on:
  schedule:
    - cron: '*/50 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python script.py
