name: Ashaq Auto Post
on:
  schedule:
    - cron: '*/30 * * * *' # تشغيل آلي كل 30 دقيقة
  workflow_dispatch: # تشغيل يدوياً عند الحاجة

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Ashaq Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python script.py
