name: V2Ray Hunter v4

on:
  schedule:
    - cron: '*/45 * * * *'
  workflow_dispatch:

jobs:
  hunt_and_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # تحديث لـ v4

      - name: Set up Python
        uses: actions/setup-python@v5 # تحديث لـ v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Hunter Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python v2ray_hunter.py
